CREATE TABLE forms (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  owner_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(255) NOT NULL,
  draft_schema JSON NULL,
  is_published TINYINT(1) NOT NULL DEFAULT 0,
  published_schema JSON NULL,
  published_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (JSON_VALID(draft_schema)),
  CHECK (JSON_VALID(published_schema))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE form_submissions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  form_id BIGINT UNSIGNED NOT NULL,
  responses JSON NOT NULL,
  submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_form_submissions_form
    FOREIGN KEY (form_id) REFERENCES forms(id)
    ON DELETE CASCADE,
  CHECK (JSON_VALID(responses))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
